#+title: Propositions de contributions

* Peertube

*Site du logiciel* : [[https://joinpeertube.org/][joinpeertube.org]] ([[https://sill.etalab.gouv.fr/fr/software?id=197][lien SILL]])

*Son code source* : [[https://github.com/Chocobozzz/PeerTube][github.com/Chocobozzz/PeerTube]]

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : Ministère de
l'Éducation nationale, de la Jeunesse et des Sports.

*Description du logiciel et de son usage dans l'administration* :
Peertube est une plateforme de publication de vidéos en ligne.  Cette
plateforme est déployée dans des académies (voir le site PAPILLON) et
elle est notamment associée à la plateforme interministérielle de
formation en ligne Mentor (Moodle).  Via cette plateforme, elle est
utilisée aujourd'hui par 6000 agents avec objectif à 900000 sur 3 ans.

*Idée de contribution* : le stage permettra de développer des modules
pour répondre à différents besoins spécifiques comme le fait de
remplacer une vidéo et de modifier les paramètres par défaut lors du
dépôt de fichier vidéos.  Le but est d'améliorer l'intégration de
ressources vidéos dans les formations portées par les ministères
impliqués dans Mentor.

* Thunderbird

*Site du logiciel* : [[https://www.thunderbird.net/fr/][thunderbird.net]]

*Son code source* : [[https://hg.mozilla.org/comm-central/][hg.mozilla.org/comm-central]] - voir aussi [[https://www.thunderbird.net/en-US/get-involved/][cette page]]
pour des explications sur les façons de contribuer.

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : Ministère de
l'Éducation nationale, de la Jeunesse et des Sports et ministère de
l'Enseignement supérieur, de la Recherche et de l'Innovation.

*Description du logiciel et de son usage dans l'administration* : Ce
logiciel est utilisé par de très nombreux agents publics dans maintes
administrations.  

*Idée de contribution* : Une idée de contribution serait d'améliorer le
support du protocole [[https://matrix.org/][matrix]] pour éviter l'utilisation d'un onglet de
navigateur ou d'un client lourd comme [[https://element.io/][Element]] pour l'utilisation de
[[https://www.tchap.gouv.fr/][Tchap]] et ainsi centraliser les outils de communication.  Une autre
idée serait de développer un module de supervision qui permette de
répondre à la question : « Est-ce que le système m'a bien envoyé un
email par jour pour me dire que le mail attendu n'est pas arrivé ? »

* Unitex/GramLab

*Site du logiciel* : [[https://unitexgramlab.org/fr][unitexgramlab.org]]

*Son code source* : [[https://github.com/UnitexGramLab/][github.com/UnitexGramLab]] - voir aussi [[https://unitexgramlab.org/fr/how-to-contribute][cette page]]
pour des explications sur les façons de contribuer.

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : Ministère de
l'Enseignement supérieur, de la Recherche et de l'Innovation.

*Description du logiciel et de son usage dans l'administration* :
Unitex/GramLab est utilisé par des laboratoires de recherche pour
explorer et exploiter des corpus de textes dans des projets de
recherche en linguistique et en traitement des langues naturelles.  Il
est compatible avec de nombreuses langues.  Il est utilisé aujourd'hui
par de nombreux étudiants et un agent public y contribue
régulièrement.

*Idée de contribution* : Le champ est libre - il peut s'agir d'ajout de
fonctionnalités, de correction de bugs, d'amélioration de l'interface
ou de toute autre idée discutée avec l'équipe de développement.

* Assistant RGAA

* JabRef

*Site du logiciel* : [[https://www.jabref.org][www.jabref.org]]
*Son code source* : [[https://github.com/JabRef/jabref][github.com/JabRef/jabref]] - voir aussi [[https://devdocs.jabref.org/contributing][cette page]] pour des explications sur les façons de contribuer.

*Langages de programmation* : Java

*Ministère utilisateur et porteur de la contribution* : Ministère de l’Enseignement supérieur, de la Recherche et de l’Innovation.
 
*Description du logiciel et de son usage dans l’administration :* JabRef is a leading bibliographic management software. It helps students, researchers and engineers to organize their articles and cite  them in new publications. It is used in research institutes and  universities in France and around the world (some of your university  teachers are probably using JabRef). And JabRef can help you write your internship report!

*Idées de contribution :* (The JabRef's development team will help you with your developement
- enable Word to be used with JabRef -- as implementation that means, 
implementing a GraphQL server in JabRef so that our 
JabRef-online-Word-Plugin ([[https://github.com/JabRef/JabRef-Word-Addin][github.com/JabRef/JabRef-Word-Addin]]) can also work with JabRef ([[https://github.com/JabRef/jabref/issues/6904][github.com/JabRef/jabref/issues/6904]]).
- add MindMapping-Support to JabRef. This would be an awesome feature ([[https://github.com/koppor/jabref/issues/433][github.com/koppor/jabref/issues/433]])
- add lucence search to JabRef itself. Completely rewrite the search of JabRef so that it is a) faster and b) also provides fuzzy search results
- browse our candidates for university projects at [[https://github.com/JabRef/jabref/projects/9][github.com/JabRef/jabref/projects/9]] and choose the ones you like.

* GDL : gnudatalanguage

* GlitchTip

* SEntry

* Openboard

* Spoon

* ElabFTW

* Mercator

* Libre office : Calc, Writer et Impress

* Platform manager

* Esup-Pod

* APiLos

* OpenTermsArchive
