#+title: Propositions de contributions

* Peertube

*Site du logiciel* : [[https://joinpeertube.org/][joinpeertube.org]] ([[https://sill.etalab.gouv.fr/fr/software?id=197][lien SILL]])

*Son code source* : [[https://github.com/Chocobozzz/PeerTube][github.com/Chocobozzz/PeerTube]]

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : Ministère de
l'Éducation nationale, de la Jeunesse et des Sports.

*Description du logiciel et de son usage dans l'administration* :
Peertube est une plateforme de publication de vidéos en ligne.  Cette
plateforme est déployée dans des académies (voir le site PAPILLON) et
elle est notamment associée à la plateforme interministérielle de
formation en ligne Mentor (Moodle).  Via cette plateforme, elle est
utilisée aujourd'hui par 6000 agents avec objectif à 900000 sur 3 ans.

*Idée de contribution* : le stage permettra de développer des modules
pour répondre à différents besoins spécifiques comme le fait de
remplacer une vidéo et de modifier les paramètres par défaut lors du
dépôt de fichier vidéos.  Le but est d'améliorer l'intégration de
ressources vidéos dans les formations portées par les ministères
impliqués dans Mentor.

* Thunderbird

*Site du logiciel* : [[https://www.thunderbird.net/fr/][thunderbird.net]]

*Son code source* : [[https://hg.mozilla.org/comm-central/][hg.mozilla.org/comm-central]] - voir aussi [[https://www.thunderbird.net/en-US/get-involved/][cette page]]
pour des explications sur les façons de contribuer.

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : Ministère de
l'Éducation nationale, de la Jeunesse et des Sports et ministère de
l'Enseignement supérieur, de la Recherche et de l'Innovation.

*Description du logiciel et de son usage dans l'administration* : Ce
logiciel est utilisé par de très nombreux agents publics dans maintes
administrations.  

*Idée de contribution* : Une idée de contribution serait d'améliorer le
support du protocole [[https://matrix.org/][matrix]] pour éviter l'utilisation d'un onglet de
navigateur ou d'un client lourd comme [[https://element.io/][Element]] pour l'utilisation de
[[https://www.tchap.gouv.fr/][Tchap]] et ainsi centraliser les outils de communication.  Une autre
idée serait de développer un module de supervision qui permette de
répondre à la question : « Est-ce que le système m'a bien envoyé un
email par jour pour me dire que le mail attendu n'est pas arrivé ? »

* Libre office : Calc, Writer et Impress

*Site du logiciel* :

*Son code source* :

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : 

*Description du logiciel et de son usage dans l'administration* :

*Idée de contribution* : 

* JabRef

*Site du logiciel* : [[https://www.jabref.org][www.jabref.org]]

*Son code source* : [[https://github.com/JabRef/jabref][github.com/JabRef/jabref]] - voir aussi [[https://devdocs.jabref.org/contributing][cette page]] pour des explications sur les façons de contribuer.

*Langages de programmation* : Java

*Ministère utilisateur et porteur de la contribution* : Ministère de l’Enseignement supérieur, de la Recherche et de l’Innovation.
 
*Description du logiciel et de son usage dans l’administration :* JabRef est un logiciel de gestion bibliographique de premier plan. Il aide les étudiants, chercheurs et ingénieurs à organiser leurs articles et à les citer dans leurs futures publications. Il est utilisé dans les instituts de recherche et les universités en France et dans le monde. Certains de vos enseignants utilisent probablement JabRef, et JabRef vous aidera lors de la rédaction de votre rapport de stage !

*Idées de contribution :*

/Notez que vous serez en mesure d'interagir directement avec l'équipe de développement de JabRef. Elle vous apportera son soutien lors de vos développements/
- permettre à Word d'être utilisé avec JabRef -- au niveau de l'implémentation, cela veut dire implémenter un serveur GraphQL dans JabRef afin que le greffon JabRef-online-Word ([[https://github.com/JabRef/JabRef-Word-Addin][github.com/JabRef/JabRef-Word-Addin]]) puisse aussi fonctionner avec JabRef ([[https://github.com/JabRef/jabref/issues/6904][github.com/JabRef/jabref/issues/6904]]).
- ajouter la possibilité de faire du Mind Mapping avec JabRef. Cela serait une fonctionnalité très intéressante ([[https://github.com/koppor/jabref/issues/433][github.com/koppor/jabref/issues/433]])
- utiliser Apache Lucene pour la recherche d'entrées bibliographiques dans la base de données courante. Apache Lucene est un moteur d'indexation et de recherche pour du texte. Apache Lucene est actuellment utilisé par JabRef lors de la recherche sur les fichiers PDF. Avec ce projet, la recherche basée sur Apache Lucene sera aussi utilisée pour les entrées bibliographiques.
- parcourez notre liste de tâches pour les projets universitaires sur [[https://github.com/JabRef/jabref/projects/9][github.com/JabRef/jabref/projects/9]] et choisissez celles qui vous plaisent.

* Assistant RGAA

*Site du logiciel* : https://github.com/empreinte-digitale/assistant-rgaa

*Son code source* : https://github.com/empreinte-digitale/assistant-rgaa

*Langages de programmation* : Javascript (React.js, Lodash, Babel)

*Ministère utilisateur et porteur de la contribution* : DINUM.

*Description du logiciel et de son usage dans l'administration* :
L'assistant RGAA est une extension pour Firefox et Chrome utilisé par
les auditeurs du RGAA (Référentiel général d'amélioration de
l'accessibilité) et par les développeurs de sites et d'applications
web.  À ce jour, une dizaine d'agents publics l'utilisent au
quotidien, et deux agents y contribuent déjà.

*Idée de contribution* : L'idée est de faciliter la réalisation des
audits RGAA.  L’assistant n’est pour l’instant qu’un guide pas-à-pas
dans la menée d’un audit. Il pourrait permettre de stocker les
résultats et de les exporter, par exemple vers un outil de rapport.
De même il pourrait importer des résultats d’audit partiel réalisés
par des outils automatiques tels que Tanaguru ou Asqatasun.  La DINUM
travaille déjà sur cette contribution, notamment en explorant le
format standardisé du W3C pour les rapports d’audits WCAG-EM-Report
Tool.

* Unitex/GramLab

*Site du logiciel* : [[https://unitexgramlab.org/fr][unitexgramlab.org]]

*Son code source* : [[https://github.com/UnitexGramLab/][github.com/UnitexGramLab]] - voir aussi [[https://unitexgramlab.org/fr/how-to-contribute][cette page]]
pour des explications sur les façons de contribuer.

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : Ministère de
l'Enseignement supérieur, de la Recherche et de l'Innovation.

*Description du logiciel et de son usage dans l'administration* :
Unitex/GramLab est utilisé par des laboratoires de recherche pour
explorer et exploiter des corpus de textes dans des projets de
recherche en linguistique et en traitement des langues naturelles.  Il
est compatible avec de nombreuses langues.  Il est utilisé aujourd'hui
par de nombreux étudiants et un agent public y contribue
régulièrement.

*Idée de contribution* : Le champ est libre - il peut s'agir d'ajout de
fonctionnalités, de correction de bugs, d'amélioration de l'interface
ou de toute autre idée discutée avec l'équipe de développement.

* Spoon

*Site du logiciel* :

*Son code source* :

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : 

*Description du logiciel et de son usage dans l'administration* :

*Idée de contribution* : 

* Esup-Pod

*Site du logiciel* : [[https://www.esup-portail.org/wiki/display/ES][www.esup-portail.org]]

*Son code source* : [[https://github.com/EsupPortail/Esup-Pod][github.com/EsupPortail/Esup-Pod]]

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : Université de
Lille.

*Description du logiciel et de son usage dans l'administration* : 

*Idée de contribution* : 

* GDL : gnudatalanguage

*Site du logiciel* :

*Son code source* :

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : 

*Description du logiciel et de son usage dans l'administration* :

*Idée de contribution* : 

* GlitchTip

*Site du logiciel* :

*Son code source* :

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : 

*Description du logiciel et de son usage dans l'administration* :

*Idée de contribution* : 

* Sentry

*Site du logiciel* :

*Son code source* :

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : 

*Description du logiciel et de son usage dans l'administration* :

*Idée de contribution* : 

* Openboard

*Site du logiciel* :

*Son code source* :

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : 

*Description du logiciel et de son usage dans l'administration* :

*Idée de contribution* : 

* ElabFTW

*Site du logiciel* : [[https://www.elabftw.net][ElabFTW]]

*Son code source* : [[https://github.com/elabftw/elabftw][github.com/elabftw/elabftw]]

*Langages de programmation* : PHP/Javascript/HTML

*Ministère utilisateur et porteur de la contribution* : INRAE

*Description du logiciel et de son usage dans l'administration* :
L'outil est utilisé dans plusieurs établissements publics ainsi que
des laboratoires Européens en tnat que cahier de laboratoire
électronique.

*Idée de contribution* : L'objet du stage serait de travailler sur un
interfaçage avec un appareil mobile (liseuse, tablette,...) avec une
possibilité de travailler sans connexion internet.

* Mercator

*Site du logiciel* : [[https://github.com/dbarzin/mercator][Mercator]]

*Son code source* : [[https://github.com/dbarzin/mercator][github.com/dbarzin/mercator/]]

*Langages de programmation* : HTML/PHP

*Ministère utilisateur et porteur de la contribution* : Direction
technique de l'innovation / Direction générale de l'Aviation civile

*Description du logiciel et de son usage dans l'administration* :
Mercator permet d'élaborer une cartographie d'un système d'information
afin d'être capable de mieux anticiper et faire face aux problèmes de
sécurité du système d'information en question.

*Idée de contribution* : À discuter.

* Platform manager

*Site du logiciel* : 

*Son code source* : [[https://pfmanager.loria.fr][pfmanager.loria.fr]]

*Langages de programmation* : 

*Ministère utilisateur et porteur de la contribution* : MESRI/CNRS

*Description du logiciel et de son usage dans l'administration* : Au
sein du laboratoire Loria (UMR 7503 CNRS / Inria / Université de
Lorraine), nous utilisons plusieurs plateformes en soutien de la
recherche. Nous avons créé l’outil 'Platform manager' pour nous aider
à gérer ces installations: projets en cours, équipements, utilisateurs

*Idée de contribution* : L'objectif du stage sera d'apporter deux
fonctionnalités à ce logiciel pour 1) l'ajout d'un module de
réservation d'équipement avec calendrier, 2) la génération automatique
de pages wiki Gitlab par projet.

* APiLos

*Site du logiciel* :

*Son code source* :

*Langages de programmation* :

*Ministère utilisateur et porteur de la contribution* : 

*Description du logiciel et de son usage dans l'administration* :

*Idée de contribution* : 

* OpenTermsArchive

*Site du logiciel* : [[https://opentermsarchive.org][opentermsarchive.org]]

*Son code source* : [[https://github.com/ambanum/OpenTermsArchive][github.com/ambanum/OpenTermsArchive]]

*Langages de programmation* : Javascript

*Ministère utilisateur et porteur de la contribution* : Ministère de
l'Europe et des affaires étrangères.

*Description du logiciel et de son usage dans l'administration* :
OpenTermsArchive est utilisé pour suivre les stratégies des grandes
plateformes numériques et pour identifier des leviers diplomatiques
dans les échanges avec elles. Au sein du PEReN (Ministère des
finances), OpenTermsArchive est utilisé pour suivre les évolutions des
conditions d'utilisation des fournisseurs de service par type
d'industrie (en particulier plateformes de mise en relation).  Au sein
de l'autorité de la concurrence, les agents en charges d'enquêtes
peuvent accéder aux conditions d'utilisation des fournisseurs de
services à toute date afin de mener des investigations détaillées.

*Idée de contribution* : 
L'objectif du stage sera de maintenir et de
compléter les descriptions de services qui sont suivis et archivés dans
OpenTermsArchive. En effet, au fur et à mesure des évolutions des documents,
ils peuvent être déplacés vers d'autres URLs, leur contenu peut être modifié et
il faut les filtrer d'une nouvelle manière pour éviter du bruit dans les
changements détectés. Toute liberté sera donnée pour expérimenter des moyens
d'outiller et d'automatiser ces mises à jour cruciales pour le bon
fonctionnement du service. Ces expérimentations seront co-construites et
évaluées par l'équipe coeur, qui pourra le cas échéant allouer des ressources
afin d'aider la personne en stage à industrialiser la solution et la mettre
entre les mains d'un grand nombre d’utilisateurs.


